### ISSUE TITLE
registration problem

### ISSUE THREAD

**Issue by zxncc** [bbbbbbzhou/APA2Seg-Net#3]
Hello,I run your code,but I didn't find the registration result.Can you tell me how to use the registration code？

**Comment by zxncc** [comment]
I can't enter the BioImage Suite Web website.

**Comment by bbbbbbzhou** [comment]
Hi, the command-line version of BIS can be found via the link below, which is the same as the BIS link posted on this Github page.
https://bioimagesuiteweb.github.io/bisweb-manual/CommandLineTools.html

Please follow the instruction on the webpage to install the BIS on your local computer. 
We do not provide the script for running the BIS because the script is outdated and doesn't match with the newest version of the BIS. However, the registration step is rather easy to do. You can have your segmentation volume ready. In BIS, simply use the extract-surface function command to extract the point cloud, and then run the registration function command.

**Comment by zxncc** [comment]
Hello,I can't enter the link(http://bisweb.yale.edu/binaries/binaries.html).So I can't download BIS.

**Comment by bbbbbbzhou** [comment]
Please check the alternative link via npm
https://www.npmjs.com/package/biswebnode/v/1.1.0-a8

You should be able to install it with:
Install node.js v 12
sudo npm install -g biswebnode
